@startuml
left to right direction

state 管理者トップ

state ブロックワード{
    state ブロックワード追加
    state ブロックワード編集
    state ブロックワード一覧
}

state 通報履歴
    state パスワード{
    state パスワードリセット
    state パスワード再設定
}

state タグ追加更新削除

管理者トップ -->ブロックワード追加
管理者トップ <--ブロックワード追加
管理者トップ -->ブロックワード編集
管理者トップ <--ブロックワード編集
管理者トップ -->ブロックワード一覧
管理者トップ <--ブロックワード一覧

管理者トップ ->通報履歴
管理者トップ <-通報履歴
管理者トップ ->パスワードリセット
管理者トップ <-パスワードリセット
メール -->パスワード再設定
管理者トップ ->タグ追加更新削除
管理者トップ <-タグ追加更新削除


@enduml