@startuml
left to right direction

entity 学生 {
  学生id [PK]
  --
  名前
  住所
  学校名
  電話番号
  メアド
  パスワード
}

entity 企業 {
    企業ID[PK]
    --
    企業名
    住所
    電話番号
    メアド
    パスワード
}

entity 履歴書 {
    履歴書ID[PK]
    --
    学生ID [FK]->学生
    企業ID [FK]->企業
    --
    履歴書ナンバー
    趣味特技
    自己PR
    証明写真No
    履歴書評価してほしいですか判別列

}

entity 学歴職歴 {
        学歴職歴ID[PK]
        --
        履歴書ID[FK]->履歴書
        --
        学歴職歴名

}

entity 資格 {
        資格ID[PK]
        --
        履歴書ID[FK]->履歴書
        --
        資格名
}

entity 匿名掲示板ルーム {
    匿名掲示板ID[PK]
    --
    企業ID[FK]
}
entity 匿名掲示板投稿 {
    メッセージID[PK]
    --
    匿名掲示板ID[Fk]
    学生ID[FK]
}


entity トークルーム {
    トークルームID[PK]
    --
    学生ID[Fk]->学生
    企業ID[Fk]->企業
}

entity トーク内容 {
    メッセージID[PK]
    --
    トークルームID[Fk]->トークルーム
    発信者どっちか判定情報
}

entity 気になるオファー {
    学生ID[PK][Fk]->学生
    企業ID[PK][Fk]->企業
    オファーか気になる判別列[PK]
}

entity 企業情報{
     企業ID[PK][Fk]->企業
     --
     企業ページレイアウトNo
     etc...(思いついたら追加しようね)
}

entity エントリー{
        エントリーID[PK]
        --
        履歴書ID[fk]
}

entity 履歴書評価メッセージ{
    返信ID[PK]
    --
    履歴書ID[FK]
    --
    返信メッセージ

}

entity NGワード{
    NGワードID[PK]
    --
    NGワードそのもの
}

entity 通報メッセージ{
    メッセージID [PK][FK]
    匿名掲示板ID [PK][FK]
    トークルームID [PK][Fk]
    --
    通報された回数カウント
}

履歴書 "1" -- "*" 履歴書評価メッセージ
履歴書 "1" -- "1" エントリー
企業 "1"--"*" エントリー
匿名掲示板投稿 "*" -- "1" 学生
匿名掲示板ルーム "1" -- "1" 企業
匿名掲示板投稿 "*"--"1" 匿名掲示板ルーム
学生 "1"--"*" 履歴書
履歴書 "1"--"*" 学歴職歴  
履歴書 "1"--"*" 資格
学生 "1"--"*"  気になるオファー
気になるオファー "*"--"1"企業
学生 "1"--"*"  トークルーム
トークルーム "1"--"*" トーク内容
企業 "1"--"1" 企業情報
トークルーム "*"--"1" 企業 

@enduml
