@startuml
left to right direction
state 簡易画面遷移図{


state 新規登録 #00FF00 {
    state 企業登録
    state 学生登録
}

state 初期ページ #00FF00 : 学生か、企業かを選んでログインや\n新規登録を選ぶ初期ページ
state ログインページ #00FF00{
    state 企業ログイン
    state 学生ログイン
}
state トップページ :・色々なページに遷移するホーム的なページ\n検索フォーム、\n カレンダー \n 利用しているトークルーム \n 匿名掲示板への遷移 \n マイページへの遷移 
state トークページ #Skyblue
state 企業ページ #Skyblue :企業の理念やお給料等の学生が知りたい\n情報等を載せた紹介ページ
state エントリーページ #Skyblue:履歴書を提出し、エントリーをするページ
state エントリー完了 #Skyblue :エントリーしたことを確認
state 検索結果 #Skyblue :学生が検索した際にヒットした企業を表示
state マイページ #Pink :設定系の機能をまとめた場所

state 学生側設定{
state 履歴書作製ページ #Pink :履歴書を作製して保存できる
state 受けたオファー #Pink :受けたオファーリストを表示
state 気になるリスト #Pink :気になるボタンで登録した企業を表示
state 閲覧履歴 #Pink :閲覧した企業の履歴を表示
} 

state 企業側設定{
    state 企業ページ編集 #Pink :企業ページのレイアウトをここで編集
}

state 設定ページ #Pink :住所やパスワード等の自身の情報を管理



state 匿名掲示板 #Yellow :匿名で多対多での掲示板
state カレンダー #LightGrey :自身のスケジュール管理


新規登録->初期ページ
新規登録<-初期ページ

初期ページ->ログインページ
初期ページ<-ログインページ

ログインページ-->トップページ
ログインページ<--トップページ

トップページ-->検索結果
トップページ -> カレンダー
トップページ -> カレンダー
検索結果-->トップページ
検索結果-->企業ページ

企業ページ-->トークページ
企業ページ-->エントリーページ
企業ページ<--エントリーページ
企業ページ<--トークページ

エントリーページ-right->エントリー完了
エントリー完了-->トップページ

トップページ-right->匿名掲示板
トップページ<--匿名掲示板
トップページ-up->企業ページ
トップページ<-up-企業ページ
トップページ-->マイページ
トップページ-up->トークページ
トップページ<-up-トークページ

マイページ-left->トップページ
マイページ-->履歴書作製ページ
マイページ-->閲覧履歴
マイページ-->気になるリスト
マイページ-->受けたオファー
マイページ-->設定ページ
マイページ-->企業ページ編集

マイページ<--履歴書作製ページ
マイページ<--閲覧履歴
マイページ<--気になるリスト
マイページ<--受けたオファー
マイページ<--設定ページ



}
@enduml