@startuml
left to right direction
state ユーザー登録関係{


state 学生新規登録 #LightGreen {
    
}

state 企業ログイン #LightGreen{
}

state 企業新規登録 #LightGreen{
}

state 学生ログイン#LightGreen{

}

学生ログイン -> 企業ログイン
学生ログイン <- 企業ログイン

学生新規登録 -> 企業新規登録
学生新規登録 <- 企業新規登録 

学生新規登録 --> 学生ログイン
学生新規登録 <-- 学生ログイン
}



state トップページ{
state 学生用トップページ#LightPink{

}

学生ログイン --> 学生用トップページ
企業ログイン --> 企業用トップページ

state 企業用トップページ#LightPink{

}


}

state カレンダー#Gray{

}

state マイページ {
    state 学生用マイページ#LightYellow
    state 企業用マイページ#LightYellow

}

企業用トップページ -->企業用マイページ
学生用トップページ -->学生用マイページ

state ユーザー設定
state 閲覧履歴

state トークルーム{

}

企業用トップページ  -right-> トークルーム
学生用トップページ -right-> トークルーム

企業用トップページ  -left-> カレンダー
学生用トップページ -left->  カレンダー

学生用マイページ -left-> ユーザー設定
企業用マイページ -left-> ユーザー設定

学生用マイページ -right-> 閲覧履歴

企業用マイページ  -right-> 企業ページ編集
企業用マイページ --> オファーを送った学生リスト
学生用マイページ  -->オファーリスト
オファーリスト -up-> 企業ページ
学生用マイページ  -->気になるリスト

学生用トップページ -left-> お悩み掲示板一覧
学生用トップページ -left-> お悩み掲示板
お悩み掲示板一覧 -left-> お悩み掲示板

トップページ-up-> 退会確認画面
退会確認画面-up-> 退会画面
退会画面->ユーザー登録関係

学生用マイページ --> 履歴書ページ
履歴書ページ-->履歴書編集ページ

学生用トップページ -right-> 企業検索結果ページ
企業検索結果ページ --> 企業ページ
企業ページ --> エントリーページ

エントリーページ-->エントリー完了表示
エントリー完了表示 --> 企業ページ

企業ページ<-down-閲覧履歴
企業ページ-up->トークルーム

企業ページ -->イベント予約
学生用トップページ -left-> 新着イベント情報
新着イベント情報 ->イベント予約

state お悩み掲示板一覧
state お悩み掲示板
state 履歴書ページ
state 履歴書編集ページ


state 企業検索結果ページ
state 企業ページ #MediumPurple

state エントリーページ
state エントリー完了表示


state 企業ページ編集

@enduml